language: go
go:
- '1.11'
script:
- go test
deploy:
  provider: heroku
  api_key:
    secure: Mq4Ys8AqvTypFhm6e8MtOyGEQeo/cW9CjqJM2d0h9tnFEgR5Xx7LquECOs55zdmsb6pqI5P2y3efGvshBSal4aLbTwaTxZk7Ga1TzBM1SRzAWR1f4zOgGYvC2KuAYCmf5RtJy6YZ9C6S8rxo85Zr/gL1QQjkteYeZByFISIijuSiDfhMZ0MSHkDPc8ZsPfpiJdPpjqnNfKRifc7ztfQwGPr6vZpJWhrGRaX6vXeyJkfaPbtWJ/JE90FbJDhTsxJaCrHZzySKjNf+R4F/GlYaty/3bpxbf5fWGt7VwhNZboS36Mlqg2cuaUqmS7vCDjGxmlTtFLVbca+uGN4zBCySaXNsMMAVBSlds8j2Dlrtrg+b+astMpeuImFcm49eYRBmc3yDDhtsRXxFjXdQmeBs1JKykMl7w6pdaecEZWZywvjKJVEgf6YL/C9k95Ekd5XHeJWvdV0KZdq5l+u1hbD7PSgC6r91AoB7pX/86NYHtkOtGWgpoCgHdWPRcXwww9DxaPbt32aPqQSq1XGat7jzjzH6s07wGe5blQm1+gYjYgWsa86N4DGCIMGdpT6E6OLw8Z0rQBPa4C5Y/DjcL0Xvheso99STa8N8jbkBkhjmwEMclvsIP1U8EbTrOZyFduxhyBb1eJtsiwYM9ffipok0SoW1TqP3VSROb3Ei07peQlA=
  app: rsoi-lab1
  on:
    repo: reijo1337/rsoi1
